### ISSUE TITLE
Categroy Generation

### ISSUE THREAD

**Issue by wicast** [LucasNova/json2ue4#35]
There will be an error when packing.
`PackagingResults: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.`

Category should use when function or field is exposing to blueprint.

**Comment by LucasNova** [comment]
Hi, I wasn't think anybody need generated structs outside of game modules. Will make category generation as soon as possible.

**Comment by LucasNova** [comment]
Done
